apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  namespace: default
  labels:
    app: brain-tasks
spec:
  selector:
    app: brain-tasks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
