version: 0.0
os: linux

files:
  - source: /
    destination: /tmp/app  # CodeDeploy copies your repository files here

hooks:
  AfterInstall:
    - location: scripts/deploy.sh  # This script will run your kubectl commands
      timeout: 300                 # Max time in seconds for the deployment step
      runas: root
